[tool.poetry]
name = "crudpython"
version = "0.1.0"
description = "Criacao de um Crud em Python"
authors = ["Miguel Salas"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
